# Generated by Django 5.2.2 on 2025-06-08 07:14

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCreditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('methodology', models.CharField(choices=[('agroforestry', 'Agroforestry'), ('conservation_ag', 'Conservation Agriculture'), ('organic', 'Organic Farming'), ('reforestation', 'Reforestation')], max_length=50)),
                ('start_date', models.DateField()),
                ('verification_standard', models.CharField(choices=[('verra', 'Verra'), ('gold_standard', 'Gold Standard'), ('acr', 'American Carbon Registry'), ('custom', 'Custom Methodology')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='kyc_documents/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('physical_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarbonCreditIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_id', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('verification_report', models.FileField(upload_to='verification_reports/')),
                ('verification_body', models.CharField(max_length=200)),
                ('transaction_id', models.CharField(max_length=100)),
                ('is_retired', models.BooleanField(default=False)),
                ('retired_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.carboncreditproject')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=100)),
                ('installation_date', models.DateField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='carboncreditproject',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile'),
        ),
        migrations.CreateModel(
            name='HederaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('did', models.CharField(blank=True, max_length=200, null=True)),
                ('did_document', models.JSONField(blank=True, null=True)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_balance_check', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('title_deed_document', models.FileField(blank=True, null=True, upload_to='title_deeds/')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gps_coordinates', models.TextField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('verification_method', models.CharField(blank=True, choices=[('satellite', 'Satellite Imagery'), ('survey', 'Professional Survey'), ('gps', 'GPS Measurement'), ('manual', 'Manual Verification')], max_length=20, null=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_owner', to='farmer.farmerprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carboncreditproject',
            name='land_parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.landparcel'),
        ),
        migrations.CreateModel(
            name='LandToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50)),
                ('serial_number', models.IntegerField()),
                ('token_metadata', models.TextField()),
                ('mint_transaction_id', models.CharField(max_length=100)),
                ('mint_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('land_parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmer.landparcel')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField()),
                ('verification_type', models.CharField(choices=[('remote', 'Remote Sensing'), ('field_visit', 'Field Visit'), ('farmer_report', 'Farmer Report'), ('community', 'Community Verification')], max_length=50)),
                ('findings', models.TextField()),
                ('is_compliant', models.BooleanField()),
                ('evidence_documents', models.FileField(blank=True, null=True, upload_to='verification_evidence/')),
                ('photos', models.FileField(blank=True, null=True, upload_to='verification_photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.carboncreditproject')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Soil Moisture'), ('temperature', 'Temperature'), ('rainfall', 'Rainfall'), ('ndvi', 'NDVI (Vegetation Index)')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('reading_date', models.DateTimeField()),
                ('source', models.CharField(choices=[('iot_device', 'IoT Device'), ('satellite', 'Satellite'), ('manual', 'Manual Entry')], max_length=50)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.carboncreditproject')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('account_create', 'Account Creation'), ('land_tokenize', 'Land Tokenization'), ('credit_issuance', 'Carbon Credit Issuance'), ('credit_transfer', 'Credit Transfer'), ('credit_retire', 'Credit Retirement')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('details', models.JSONField()),
                ('network_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('verification_method', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.landparcel')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
