# Generated by Django 5.2.2 on 2025-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtoken',
            name='mint_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
