# Generated by Django 5.2.2 on 2025-06-12 18:11

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_landtoken_mint_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carboncreditissuance',
            options={'ordering': ['-issuance_date'], 'verbose_name': 'Carbon Credit Issuance', 'verbose_name_plural': 'Carbon Credit Issuances'},
        ),
        migrations.AlterModelOptions(
            name='carboncreditproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Carbon Credit Project', 'verbose_name_plural': 'Carbon Credit Projects'},
        ),
        migrations.AlterModelOptions(
            name='practiceverification',
            options={'ordering': ['-verification_date'], 'verbose_name': 'Practice Verification', 'verbose_name_plural': 'Practice Verifications'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['-reading_date'], 'verbose_name': 'Sensor Data', 'verbose_name_plural': 'Sensor Data'},
        ),
        migrations.RemoveField(
            model_name='practiceverification',
            name='evidence_documents',
        ),
        migrations.RemoveField(
            model_name='practiceverification',
            name='photos',
        ),
        migrations.AddField(
            model_name='carboncreditissuance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 12, 18, 10, 14, 40406, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carboncreditissuance',
            name='retirement_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carboncreditissuance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='carboncreditissuance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='carboncreditissuance',
            name='verification_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 12, 18, 10, 42, 518426, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carboncreditproject',
            name='expected_credits_per_year',
            field=models.DecimalField(decimal_places=2, default=1000000, help_text='Estimated carbon credits per year (tons CO2e)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carboncreditproject',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carboncreditproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='compliance_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Compliance score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 12, 18, 10, 55, 291605, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='next_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_followup', 'Requires Follow-up')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='practiceverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 12, 18, 11, 2, 269178, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in tons of CO2 equivalent', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuances', to='farmer.carboncreditproject'),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='token_id',
            field=models.CharField(blank=True, help_text='Hedera token ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Hedera transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='carboncreditissuance',
            name='verification_report',
            field=models.FileField(upload_to='verification_reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='carboncreditproject',
            name='methodology',
            field=models.CharField(choices=[('agroforestry', 'Agroforestry'), ('conservation_ag', 'Conservation Agriculture'), ('organic', 'Organic Farming'), ('reforestation', 'Reforestation'), ('biochar', 'Biochar Application'), ('livestock', 'Improved Livestock Management')], max_length=50),
        ),
        migrations.AlterField(
            model_name='practiceverification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='farmer.carboncreditproject'),
        ),
        migrations.AlterField(
            model_name='practiceverification',
            name='verification_type',
            field=models.CharField(choices=[('remote', 'Remote Sensing'), ('field_visit', 'Field Visit'), ('farmer_report', 'Farmer Report'), ('community', 'Community Verification'), ('drone', 'Drone Survey'), ('satellite', 'Satellite Imagery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='farmer.carboncreditproject'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sensor_type',
            field=models.CharField(choices=[('soil_moisture', 'Soil Moisture'), ('temperature', 'Temperature'), ('rainfall', 'Rainfall'), ('ndvi', 'NDVI (Vegetation Index)'), ('soil_carbon', 'Soil Carbon Content'), ('ph', 'Soil pH')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='source',
            field=models.CharField(choices=[('iot_device', 'IoT Device'), ('satellite', 'Satellite'), ('manual', 'Manual Entry'), ('drone', 'Drone Survey')], max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('verify', 'Verify'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='verification_evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio Recording'), ('geojson', 'GeoJSON')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='farmer.practiceverification')),
            ],
            options={
                'verbose_name': 'Verification Evidence',
                'verbose_name_plural': 'Verification Evidence',
            },
        ),
    ]
